### ISSUE TITLE
Splash: 파이어베이스 로그인 구현

### ISSUE THREAD

**Issue by youneeo** [LESSERAFIM-Aespa/TripMate#100]
## **Feature Description**

- 파이어베이스로 페이스북 로그인 연동을 구현합니다.

## **Todo list**

- [x] 파이어베이스로 페이스북 로그인 구현하기
- [x] 페이스북 로그인시 파이어베이스 인증이 안되는 문제 
- [x]  페이스북 로그인시 아이디와 이미지가. null 값으로 반환되는 문제
