### ISSUE TITLE
Community : 비지니스로직 분리

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#102]
## **Feature Description**

-  MVVM 코드 분리

## **Todo list**

- [x] Community UI
- [x] FirebaseDBRemoteDataSource 추가
- [x] Community RepositoryImpl 추가
- [x] Remote& Domain 데이터클래스 추가
- [x] 도메인 레파지토리 추가
- [x] 도메인 usecase추가
- [x] 뷰모델&팩토리 수정
- [x] Fragment에서 적용
