### ISSUE TITLE
Community : 북마크 관련 로직 분리

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#104]
## **Feature Description**

- 커뮤니티 북마크관련 뷰모델을 합치고 로직을 분리합니다.

## **Todo list**

- [x] remote&domain 데이터클래스 추가했습니다.
- [x] 도메인 usecase를 추가했습니다.
- [x] 도메인 레파지토리를 수정했습니다.
- [x] remote 레파지토리를 수정했습니다.
- [x] FirebaseDBRemoteDataSource를 수정했습니다.
- [x] 뷰모델&팩토리를 수정했습니다.
- [x] 북마크 식별키를 라이브데이터로 관리하고 RDB에 저장합니다.
- [x] 북마크 여부를 토스트 메시지로 표시합니다.
