### ISSUE TITLE
UserProfile Fragment 구현하기

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#115]
## **Feature Description**

UserProfile Fragment

- 유저프로필에는 해당 사용자의 썸네일 이미지, 닉네임, 자기소개를 보여준다.
- 유저프로필에는 해당유저가 작성한 글 목록을 사용자에게 보여준다.

## **Todo list**

- [x]  (필수) 프로필UI 구현
- [x]  (필수) 사용자 닉네임, 이미지, 자기소개 받아와 View에 반영하기
- [x]  (필수) 사용자 작성한 글 목록 받아와 Recyclerview에 표시하기
