### ISSUE TITLE
MyPage & Community UI를 변경했습니다.

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#116]
## **Feature Description**

- MyPage의 Board UI를 수정했습니다.
- Community의 좋아요버튼을 수정했습니다.

## **Todo list**

- [x] 좋아요 버튼 수정
- [x] MyPage/Board : 클릭이벤트 추가 (썸네일 클릭 시 intent데이터를 가지고 Community Detail페이지로 넘어갑니다.)
- [x]  Community의 어댑터에있던 intent관련 코드를 프래그먼트로 이동했습니다.
- [x] MyPage & Community에서 RDB에 저장된 addedImage가 없다면 기본이미지, 있다면 해당 이미지로 앱에 표시됩니다.
