### ISSUE TITLE
Home& MyPage 에서 아이템을 클릭 시 동일하게 조회수가 1씩 오르게 적용

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#124]
## **Feature Description**

- 기존에는 Home& MyPage에서 단순히 업데이트된 RDB를 받아왔다면, Home&MyPage에서도 클릭하면 조회수가 추가된 부분을 업데이트 하도록 수정합니다.

## **Todo list**

- [x] remote레파지토리 수정
- [x] 도메인 레파지토리 수정
- [x] 도메인 usecase 추가
- [x] 뷰모델& 팩토리 수정
- [x] HomeFragment 클릭이벤트 수정
- [x] CommunityDeatail에서 데이터를 넣어주는 부분 추가
- [x] MyPageFragment 클릭이벤트 수정
- [x] MyPage 뷰모델&팩토리 수정
