### ISSUE TITLE
커뮤니티 수정/보완작업

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#128]
## **Feature Description**

커뮤니티 수정&보완작업

- 커뮤니티 3개의 페이지에서 수정 및 보완작업을 진행합니다.
- 앱 중간발표 전 다듬는 작업을 진행합니다.

## **Todo list**

메인페이지

- [ ] - 검색기능

 글쓰기페이지

- [ ] 글쓰기페이지 제목 & 내용부분 간격맞추기
- [ ] 글쓰기페이지에서 이미지 가져올때 이미지 사이즈 화면에 거의 꽉차게 키우기

커뮤니티 디테일페이지

- [ ] 게시글 이미지 사이즈 키우기
- [ ] 게시글페이지 좋아요, Views, 내용 제목과 시작점 맞추
- [ ] 게시글 제목 오른쪽에 딱 달라붙지않게 간격주기 , 제목과 똑같이 내용도 오른쪽 제목과 똑같이 간격맞추기
- [ ] (필수)수정버튼클릭시 글 수정기능 구현.
- [ ] 홈에서 인기글 클릭시 조회수 최신화 안되는 이슈
- [ ] 내가 쓴 글 삭제하기
