### ISSUE TITLE
MyPage : 블로그 북마크 + 커뮤니티 북마크를 스크랩탭에 모두 표시하기 

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#129]
## **Feature Description**

- 레파지토리가 많아서 전체적으로 이름 정리& 패키지 이동 했습니다.
- 블로그 &커뮤니티 데이터를 MyPage의 "스크랩 목록"에서 함께 표시해줍니다.
- RDB 추가&삭제 시 화면이 갱신됩니다. 

## **Todo list**

- [x] 패키지 이동
- [x] 함수 이름 정리
- [x] 데이터클래스 변환함수
- [x] 레파지토리 수정
- [x] 뷰모델 수정
- [x] 팩토리 수정
- [x] 데이터클래스 공용 인터페이스 추가
- [x] 블로그 &커뮤니티 데이터 타입 추가
- [x] 프래그먼트&어댑터 수정
