### ISSUE TITLE
Home UI

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#133]
## **Feature Description**

- Home화면과 탭레이아웃의 UI를 변경했습니다.

## **Todo list**

- [x] 탭 레이아웃 Scrap -> Blog로 변경
- [x] Home화면의 Scrap -> Blog로 변경
- [x] Home화면의 블로그 아이템 GridView 2줄로 레이아웃 변경
- [x] Home화면의 이동하기버튼을 변경했습니다.
