### ISSUE TITLE
로그인: 네이버로그인 파이어베이스인증 연동

### ISSUE THREAD

**Issue by youneeo** [LESSERAFIM-Aespa/TripMate#137]
## **Feature Description**

- 네이버 로그인 기능을 구현합니다
- 네이버 로그인을 할때, 할당받은 액세스 토큰을 파이어베이스의 cloud funtion 을 이용해 파이어베이스에 인증을 합니다
- 현재 서버를 파이어베이스로 두고있고, 파이어베이스 인증을 통해 생성된 uid를 기반으로 보안규칙이 설정되었고
그에맞게 uid를 비교해 게시글이 수정하는 로직이 설정되어있고,데이터관리또한 나누어지면 곤란해지는 상황으로 판단하여 받아들였습니다.
현재 참고하여 개발해보고있습니다. 로그인 구현까지는 어렵지않았지만 이미 짜여져있는 로직에 맞게 대응하느라 시간이 걸리고있습니다.
10.30 (점검) 이후에 구현되는 부분으로 받아들이고있어 현재 해당 개념에 대해 조금이라도 이해해보고자 시간을 할애하여 개발중에 있습니다.

- https://lanicc.medium.com/%ED%8C%8C%EC%9D%B4%EC%96%B4%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%97%90-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0-2-9b578407f1b3
- https://lanicc.medium.com/%ED%8C%8C%EC%9D%B4%EC%96%B4%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%97%90-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0-3-bb65a6e92447
- https://lanicc.medium.com/%ED%8C%8C%EC%9D%B4%EC%96%B4%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%A1%9C-%EB%84%A4%EC%9D%B4%EB%B2%84-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0-%EC%9D%91%EC%9A%A9%ED%8E%B8-e95fe2a719c8

참고 예제를 찾기 힘들었고, 현재 지식으로 이해하기 어려운 부분이 있어 참고자료를 위에 링크했습니다.

## **Todo list**

 커스텀토큰 : 네이버로그인시 생성되는 액세스 토큰 > firebase cloud function > 파이어베이스에  액세스되는 토큰 으로 이해하고있습니다. 

- [x] 네이버 로그인 구현
- [x] 로그인시 생성되는 토큰을 파이어베이스 Cloud Functions에 전송하여 커스텀 토큰을 생성하도록 요청
- [x] 파이어베이스 인증: 사용자 정의 토큰을 받은 후, 이 토큰을 사용하여 파이어베이스에 인증하게 됩니다. 
- [ ] Cloud Functions를 사용하여 커스텀토큰 토큰을 생성하는 로직을 구현
