### ISSUE TITLE
setting : 회원탈퇴 및 설정화면에 프로필 이미지& 로그인 타입& 이메일을 표시합니다.

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#140]
## **Feature Description**

- Home화면 "가계부 관리" -> "가계부"로 변경
- User데이터 클래스에 로그인타입을 추가했습니다.
- MVVM구조로 분리했습니다.
- 뷰모델&라이브데이터를 이용해서 데이터를 관리합니다.
- setting화면에 profileImage,  user Type (예 : goole, naver),  user email을 화면에 표시합니다.

## **Todo list**

- [x] Home UI수정
- [x] user데이터클래스 type추가 (예 : goole, naver)
- [x] remote DataSource 추가
- [x] remote 레파지토리 분리
- [x] 도메인 레파지토리 추가
- [x] 도메인 usecase추가
- [x] 뷰모델 추가
- [x] SettingActivity에 적용
