### ISSUE TITLE
UserProfle : 기능구현

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#146]
## **Feature Description**

- 게시판 아이템을 작성한 사람이 본인이면 MyPage로 이동되고, 다른 유저면 UserActivity로 이동됩니다.
- UserActivity에 저장된 유저정보를 화면상단에 표시해줍니다.
- userProfile게시판의 화면에 데이터를 표시해줍니다.
- 아이템클릭시 커뮤니티 디테일로 이동되고, 조회수가 추가됩니다.

## **Todo list**

- [x] 게시판 글 작성자의 Uid저장
- [x] user데이서 소스 재활용해서 사용하기
- [x] userprofileActivity 뷰모델&팩토리 추가
- [x] userProfile 게시판 뷰모델&팩토리 추가
