### ISSUE TITLE
커뮤니티 페이지 중간발표까지의 작업완료

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#154]
## **Feature Description**

- 리펙토링했던 코드 revert후 기존 코드를 수정 보완하여 구현하였습니다.
- 중간발표이후 리펙토링시간을통해 코드정리 및 기능분할을 하려고합니다.

## **Todo list**

1. 커뮤니티 페이지
    - [x]  조회수
        - [x]  이동한 디테일페이지에도 클릭한 조회수 반영해서 적용하기
    - [x]  좋아요 수
    - [x]  좋아요 토글
    - [x]  쓰기(이미지 X)
    - [x]  쓰기(이미지 O)
    - [ ]  커뮤니티 디테일 툴바 북마크 다이얼로그(추가기능)
    - [x]  커뮤니티 디테일 툴바 삭제 다이얼로그(추가기능)
    - [x]  게시글목록의 유저정보 클릭시 이동
        - [ ]  내 게시글목록이 출력됨(UID문제일듯)
2. 홈
    - 블로그 탭
        - [x]  북마크한 블로그 표시되는지
        - [x]  북마크한 블로그 클릭시 웹뷰보이는지
        - [x]  뒤로가기 화살표(추가)
    - 인기글 탭
        - [x]  터치시 디테일 이동여부
        - [x]  좋아요수 sort기능 동작여부
3. 블로그
    - [x]  블로그페이지 이동시 페이지 reload(추가기능) : 리스트 + 검색어삭제
    - [x]  블로그 검색결과 item 북마크 아이콘 변경(별)(추가기능)
    - [x]  웹뷰페이지 북마크
4. 마이페이지
    1. 내글목록
        - [x]  내글만 보이는지
        - [x]  터치시 디테일페이지 이동여부
        - [x]  조회수
    2. 스크랩목록
        - [x]  블로그 & 게시글 보이는지
        - [x]  클릭시 페이지이동여부
            - [x]  블로그 → 웹뷰 페이지
            - [x]  게시글 → 디테일 페이지

5. 유저페이지

- [x]  썸네일, 닉네임, 자기소개 불러와지는지
- [ ]  조회수
- [ ]  좋아요 수
- [ ]  좋아요 토글
- [ ]  유저 게시글 클릭시 디테일페이지 이동
