### ISSUE TITLE
가계부 추가 개발(통계,스크린샷 공유,EditTextFormat,버그수정)

### ISSUE THREAD

**Issue by PotatoMeme** [LESSERAFIM-Aespa/TripMate#158]
## **Feature Description**

- 가계부의 미개발부분과 개발하다 발견되 가계부 관련 버그 수정
- 통계페이지와 스크린샷 공유 같은 미개발된 파트 개발

## **Todo list**

- [x] 가계부 통계 Page
  - [x] 지출 통계 추가
  - [x] 소득 통계 추가
  - [x] 정산 기능 추가
  - [x] 스크린샥 공유

- [x] 가계부 과정리스트 
  - [x] 가계부 수정시 원금과 잔금 최신화

- [x] EditTextFormat추가
