### ISSUE TITLE
마이페이지 : 디자인변경

### ISSUE THREAD

**Issue by youneeo** [LESSERAFIM-Aespa/TripMate#164]
## **Feature Description**

- 마이페이지 디자인을 피그마에 맞게 수정합니다.
- <img width="307" alt="스크린샷 2023-11-05 오전 10 46 30" src="https://github.com/LESSERAFIM-Aespa/TripMate/assets/129308578/c6a2f8d3-002b-4449-9d5a-97a661e5de59">
취소버튼을 뒤로가기 버튼으로 대체, 확인버튼을 게시버튼으로 대체 [ 확인이 필요합니다 ]

- <img width="285" alt="스크린샷 2023-11-05 오전 10 46 11" src="https://github.com/LESSERAFIM-Aespa/TripMate/assets/129308578/a763bfa5-7809-4fde-9b85-94b851dc5296">

보시다시피 수정버튼이 상단 앱바에도 있고, 프로필이미지에도 있어 이미지만 추가해놓은 상태입니다.

## **Todo list**

- [x] 마이페이지 디자인변경
- [x] 취소,게시버튼을 어떻게 대체할지 구체적인 표기가없음 ( 수정버튼이 프로필이미지 옆에도있고 앱바에도 있음)
- [x]  수정버튼이 프로필이미지 옆에도있고 앱바에도 있음
- [x] 취소버튼을 뒤로가기 버튼으로 대체하고, 확인버튼을 게시버튼으로 대체하기
- [ ]  자기 소개 글이 스크롤 되게 처리
- [ ]  자기 소개 수정시 한줄로만 입력되는것을 줄바꿈 처리

- 할 일을 체크박스 내부에 적은 후 해당사항이 완료된경우 체크한다.
