### ISSUE TITLE
가계부 디자인 변경

### ISSUE THREAD

**Issue by PotatoMeme** [LESSERAFIM-Aespa/TripMate#174]
## **Feature Description**

- Figma 디자인 수정한내용들 xml 코드에 적용및 적용으로 앱동작 안되는부분 수정

## **Todo list**

- [x]  가계부 리스트
    - [x]  toolbar 추가
    - [x]  리사이클러뷰 item 디자인 변경
    - [x]  리사이클러뷰 item 변경에 따른 adapter수정
- [x]  가계부 Content
    - [x]  toolbar 추가
    - [x]  리사이클러뷰 item 디자인 변경
    - [x]  xml변경에 따른 코드수정
- [x]  가계부 세부 과정
    - [x]  tabbar 디자인 변경
    - [x]  날짜 나오게 수정
    - [x]  가계부 과정 리스트
    - [x]  가계부 통계
- [x]  가계부 과정 Content
- [x]  가계부 과정 디테일
