### ISSUE TITLE
홈 화면 / 블로그 UI 수정

### ISSUE THREAD

**Issue by monsterKyu** [LESSERAFIM-Aespa/TripMate#178]
## **Feature Description**

- 홈 화면은 피그마에 맞게 UI 수정
- 블로그 화면 UI 수정

## **Todo list**

- [x] 내 스크랩, 인기글, 가계부 관리 카드뷰 처리
- [x] 이동하기 이미지 버튼 이동하기와 화살표 버튼 분리
- [x] grid 2 줄에서 1줄로 관리
- [x] 블로그 추천 여행지 shape 변경
