### ISSUE TITLE
scrap&community&mypage&userprofile : UI수정

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#185]
## **Feature Description**

- scrap : 피그마에 맞게 UI를 수정했습니다.
- community : 피그마에 맞게 UI를 수정했습니다.(제목이 길어지면 아래 레이아웃과 겹쳐지는 문제를 수정했습니다.)
- mypage : 피그마에 맞게 UI를 수정했습니다.(제목이 길어지면 아래 레이아웃과 겹쳐지는 문제를 수정했습니다.)
- userprofile : 피그마에 맞게 UI를 수정했습니다.

## **Todo list**

- [x] scrap UI 수정
- [x] scrap 추천여행지 둥글게 변경
- [x] scrap 추천여행지를 클릭하면 검색이되는것을 user가 알 수 있도록 변경
- [x] community UI수정
- [x] community 뒤로가기버튼 흰색으로 변경
- [x] community 툴바 색상& 글꼴& 간격 변경
- [x] community 아이콘 색상 변경
- [x] community 제목 작성 시 엔터 -> 다음 탭으로 넘어가도록 변경
- [x] mypage UI수정
- [x] mypage 수정버튼 프로필버튼쪽으로 이동하기 
- [x] mypage 카드뷰에 프로필사진&닉네임&자기소개 모두 넣어 변경
- [x] mypage 탭레이아웃과 뷰페이저 사이에 구분선 추가하기
- [x] mypage 자기소개 작성할때 view 겹치는 부분 수정
- [x] userprofile UI 수정
- [x] userprofile 탭 레이아웃과 뷰페이저 사이에 구분선 추가하기
- [x] userprofile 카드뷰에 프로필사진&닉네임&자기소개 모두 넣어 변경
