### ISSUE TITLE
home&community&mypage&blog&login&setting : 버그&기능추가&UI수정

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#188]
## **Feature Description**

- home의 가계부탭에서 원금&예산의 레이아웃이 불규칙적이던부분을 수정합니다.
- home 로그아웃 혹은 회원탈퇴후 재가입 혹은 재 로그인시 데이터가 보이지않던 이슈를 수정합니다.
- community : 검색 기능을 추가합니다.
- community detail : 좋아요 기능을 추가합니다.
- community detail : 프로필 사진을 눌렀을때 userpage혹은 mypage로 이동되는기능 추가 합니다.
- community detail : 북마크된 게시글 수정했을때 버그를 수정합니다.
- login : 닉네임을 넣어야 로그인되도록 수정하고, sharedpreferences -> auth로 수정합니다.
- login 관련 리팩토링
- mypage : 내글 목록에서 제목이 겹쳐서 나오는 버그를 수정합니다.
- mypage : 수정버튼을 눌렀을때 닉네임, 프로필 이미지 모두 수정합니다.
- setting: 뒤로가기버튼 검은색으로 변경합니다.

## **Todo list**

- [x] home의 가계부 레이아웃을 규칙으로 변경합니다.
- [x] home: cardview의 layout을 120dp로 고정합니다.
- [x] community : 검색 기능 추가
- [ ] community: 탈퇴한 유저프로필을 클릭할경우 토스트메시지를 출력합니다.
- [x] community detail : 좋아요 기능 추가
- [x] community detail : 프로필 사진을 눌렀을때 userpage& mypage로 이동 기능 추가
- [x] community detail : 북마크된 게시글을 수정했을때 버그 개선
- [x] community detail : 데이터를 intent를 이용해서 받아오는 방식에서 RDB에서 받아오는 방식으로 수정
- [x] community detail : RDB에서 받아오는 데이터중에 하나만 라이브데이터로 관리합니다.
- [x] community detail : 리팩토링
- [x] community detail: 탈퇴한 유저프로필을 클릭할경우 토스트메시지를 출력합니다.
- [x] login : 닉네임을 넣어야 로그인이 되도록 수정
- [x] login : sharedpreferences -> auth 로 수정
- [x] userprofile : 좋아요 기능 충돌 해결
- [x] mypage : 내 글목록에서 제목이 겹쳐서 나오는 부분 수정
- [x] setting: 뒤로가기 버튼을 검은색으로 변경합니다.
- [x] setting: 회원탈퇴시 탈퇴사용자의 블로그스크랩정보 삭제합니다.
- [x] sharedPreference : 회원탈퇴시 기존의 모든 key의 data를 삭제합니다.
