### ISSUE TITLE
블로그페이지 기능수정

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#189]
## **Feature Description**

- "이미지를 클릭하면 검색합니다" 텍스트 제거
- 검색어가 없을경우 추천여행지 제안페이지 보이게합니다. 만약 사용자가 추천여행지를 클릭했을경우 검색어를 검색창에 입력되게하여 검색하도록 합니다.
- 사용자가 검샋했던페이지는 사용자가 검색 텍스트 내용을 모두 지우지않는 한 유지합니다. 만약 사용자가 검색텍스트를 모두 지운경우 혹은 검색어가 없는경우에는 추천여행지 페이지를 보여줍니다.

## **Todo list**

- [x] "이미지를 클릭하면 검색합니다" 텍스트 제거하기
- [x] 검색어에따라 실시간으로 추천여행지 혹은 검색결과 보여주기
- [x] 웹뷰페이지 다른곳으로 이동 막기
