### ISSUE TITLE
설정 페이지

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#19]
## **Feature Description**

- 내 정보에서 우측상단 톱니바퀴를 눌렀을때 보이는 페이지입니다.
- 현재 내가 로그인한 서비스(구글, 애플)정보와 내 ID(이메일)가 화면에 표시됩니다.
- 로그아웃버튼과 회원탈퇴 버튼이 있으며 클릭시 해당기능을 수행하고 로그인 화면으로 넘어갑니다.

## **Todo list**

- [x] xml 배치
- [x] firebase와 통신하여 현재 내 정보받아와 email 표시하기
- [x] 로그아웃 버튼 클릭시 firebase logout처리 
- [x] 회원탈퇴 버튼 클릭시 firebase signout처리
