### ISSUE TITLE
가계부 버그 수정및 추가 개발

### ISSUE THREAD

**Issue by PotatoMeme** [LESSERAFIM-Aespa/TripMate#190]
## **Feature Description**

- 가계부 text 나 textSize 같은 자잘한 xml 수정
- 안드로이드 33 버전 이상 경우 공유 안 되는 것 수정
- 통계 페이지 FAB 안 보이게 수정
- Theme수정 다크 모드 미지원
- 가계부 카테고리 색상선택후 저장안되는 버그 수정
- 가계부 카테고리 지우고 View 최신화 안되는 버그 수정

## **Todo list**

- [x] 가계부 text 나 textSize 같은 자잘한 xml 수정
- [x] 안드로이드 33 버전 이상 경우 공유 안 되는 것 수정
- [x] 통계 페이지 FAB 안 보이게 수정
- [x] Theme수정 다크 모드 미지원
- [x] 가계부 카테고리 색상선택후 저장안되는 버그 수정
- [x] 가계부 카테고리 지우고 View 최신화 안되는 버그 수정
