### ISSUE TITLE
Login & UserProfile& Budget&Setting & Community& MyPage : UI& 광고배너추가&버그수정

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#195]
### UI 수정
- Login : 로그인 버튼을 아래로 이동했습니다.
- UserProfile : 뒤로가기버튼을 흰색으로 변경했습니다.

### 기능 추가
- Budget & Setting : 광고 배너를 추가합니다.
- community : 검색어가 비었을 경우 모든 게시글이 화면에 추가되도록 합니다.

### 버그 수정
- MyPage : 제목이 겹치는 버그를 수정했습니다.

## **Todo list**

- [x] Budget : 광고 배너를 추가합니다.
- [x] Setting : 광고 배너를 추가합니다.
- [x] community : 검색어가 비었을때 모든 게시글이 보이게 수정합니다.
- [x] Login : 로그인버튼 위치를 조정합니다.
- [x] UserProfile : 뒤로가기버튼을 흰색으로 수정합니다.
- [x] MyPage : 제목이 프로필 사진과 겹치는 버그를 수정합니다.
