### ISSUE TITLE
홈 화면 UI수정

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#197]
## **Feature Description**

- 홈 화면의 View영역들을 조정하고 다듬습니다.

## **Todo list**

- [x] 각 CardView의 Line Padding 조정
- [x] 스크롤시 툴바제외 컨텐츠 뒷배경쪽은 흰색으로 조정
- [x] CardView의 Recyclerview Bottom BottomNavigation으로 붙이기
- [x] 가계부관리 가운데정렬
- [x] 블로그 Recyclerview Item 디자인 변경
- [x] 블로그 Recyclerview item 가운데정렬
