### ISSUE TITLE
가계부 리팩토링

### ISSUE THREAD

**Issue by PotatoMeme** [LESSERAFIM-Aespa/TripMate#198]
## **Feature Description**

- 가계부 Repository가 너무 무거움 해당 Repository를 퍼트려야함
- DataSource와 UseCase 적용이 필요
- 안쓰고 있는 함수등 삭제필요
- 이름이 적절하지 않은 함수가 있음
- 패키징이 잘안되있음

## **Todo list**

- [x] 가계부 Repository가 너무 무거움 해당 Repository를 퍼트려야함
- [x] DataSource와 UseCase 적용이 필요
- [x] 안쓰고 있는 함수등 삭제필요
- [x] 이름이 적절하지 않은 함수가 있음
- [x] 패키징이 잘안되있음
