### ISSUE TITLE
약관 및 개인정보처리방침 추가

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#209]
## **Feature Description**

- 약관과 개인정보처리방침 버튼을 설정페이지에 추가합니다.

## **Todo list**

- [x] 회원탈퇴 && 로그아웃 버튼 위치조정
- [x] 약관 및 개인정보처리방침 버튼 추가
- [x] 약관 및 개인정보처리방침 버튼클릭시 브라우저로 이동
