### ISSUE TITLE
sharedPreference, object class 에서 data source로 변경및 usecase 추가

### ISSUE THREAD

**Issue by PotatoMeme** [LESSERAFIM-Aespa/TripMate#213]
## **Feature Description**

- 현재 sharedPreference가 object class 로 동작하고 있음 해당 object를 다른 datasource처럼 class 와 usecase등  리팩토링이 필요

## **Todo list**

- [x] object를 data source class 로 변경
- [x] 함수등을 repositoy로 di 적용
- [x] UseCase를 적용하여 ViewModel에서 쓰기쉽게 변경
