### ISSUE TITLE
1.0.4 ~1.0.5 버전 : login&splash&setting&home&scrap - Bug,Feat,Ui 수정 

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#225]
### BUG
- login : 닉네임 입력 시 무한 엔터 되던 부분 수정했습니다.
- login : 회원탈퇴를 하지않고 앱을 삭제 후 재 설치 했을때 발생했던 에러를 수정했습니다.
- 앱을 완전히 종료 후 재 실행했을때 다시 구글 로그인버튼을 눌러야되는 부분을 수정했습니다.

### FEAT
- splash : 구글스토어에 업데이트가 있는지 확인하고, 업데이트가 있다면 업데이트하고, 그렇지 않으면 바로 접속됩니다.
- 접속했을때 토스트메시지를 추가했습니다.
- setting : 시스템 뒤로가기를 눌렀을때 종료 다이얼로그를 추가했습니다.

### UI
- 가계부 과정 : 메모 최대글자수를 99자까지 수정했습니다.
- home : 가계부 관련 텍스트 정렬이 쏠리는 부분 수정했습니다. 
- scrap : 텍스트가 좌측으로 쏠리는 부분 수정했습니다.

## **Todo list**

- [ ] login : 닉네임 입력창 무한엔터 되던부분 수정
- [ ] 회원탈퇴를 하지않고 앱을 삭제 후 재 설치 했을때 발생했던 에러를 수정
- [ ] splash 구글 스토어에 업데이트 유무 확인 후 업데이트 가능 하도록 수정
- [ ] 앱을 완전히 종료 후 재 실행했을때 다시 구글 로그인버튼을 눌러야되는 부분 수정
- [ ] setting : 시스템 뒤로가기버튼 종료 다이얼로그 추가
- [ ] home & scrap : 레이아웃 정렬
- [ ] 가계부 : 글자수 수정
