### ISSUE TITLE
scrap 페이지 구현

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#25]
## **Feature Description**

- Naver 블로그 API를 이용해서 블로그를 검색하는 페이지입니다.
- 아이템을 클릭시 해당 블로그를 웹뷰를 이용해서 표시해줍니다.

## **Todo list**

- [x] UI변경
- [x] searchView를 이용해서 블로그검색
- [x] 리사이클러뷰를 이용해서 데이터 표시
- [x] 항목 클릭 시 해당 link를 이용해서 웹뷰에 블로그 내용 표시
