### ISSUE TITLE
가계부 (Budget) xml 디자인

### ISSUE THREAD

**Issue by PotatoMeme** [LESSERAFIM-Aespa/TripMate#48]
## **Feature Description**

- 가계부(가계부 관리),BudgetList
- 가계부_세부_과정,BudgetDetail
- 가계부_추가,BudgetAdd
- 가계부_수정,BudgetEdit
- 가계부_삭제,BudgetRemove

## **Todo list**

- [x] 가계부(가계부 관리),BudgetList
- [x] 가계부_세부_과정,BudgetDetail
- [x] 가계부_추가,BudgetAdd
- [x] 가계부_수정,BudgetEdit

**Comment by PotatoMeme** [comment]
- [ ] 가계부 과정 보기
- [ ] 가계부 과정 추가수정
- [ ] 프래그먼트 액티비티로
