### ISSUE TITLE
게시판 : 작성,상세 페이지 구현

### ISSUE THREAD

**Issue by youneeo** [LESSERAFIM-Aespa/TripMate#57]
## **Feature Description**

- 게시판 작성페이지에서 뒤로가기 버튼을 누를시에 게시판 작성 페이지에서 메인페이지로 돌아간다.
- 게시판 작성페이지에서 공유 버튼을 누를시에 게시글 상세페이지로 넘어간다. 

## **Todo list**

- [x] 게시글 작성페이지에 공유버튼을 눌렀을때, 게시판 상세페이지로 연결되고,뒤로가기페이지를 눌렀을때,전화면으로 돌아가게끔 구현
- [x] 게시글을 작성했을때, 파이어베이스에 저장되도록구현
- [ ] 게시글을 불러올때, 파이어베이스에서 저장된 데이터들을 불러올 수 있도록 구현
- [ ] 이미지버튼을 눌렀을때, 이미지를 업로드 할 수 있도록 구현
