### ISSUE TITLE
Home : UI구성

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#61]
## **Feature Description**

- 상단 프로필 사진과 "${닉네임} 님 환영합니다." 텍스트 표시
- 첫번째 줄 :  title과 데이터 표시 리사이클러뷰
- 두번째 줄 :  title과 데이터 표시 리사이클러뷰
- 세번째 줄 :  title과 가계부 항목을 표시할 수 있는데 뷰
- 각 줄의 화살표 버튼

## **Todo list**

- [x] 프로필 사진, 텍스트뷰 만들기
- [x] 첫번째줄 title, 리사이클러뷰
- [x] 두번째 줄 title, 리사이클러뷰
- [x] 세번째 줄 title, 가계부 레이아웃
- [x] 화살표 버튼
- [x] 버튼클릭시 각각의 프래그먼트로 이동
