### ISSUE TITLE
Home : 기능 구현

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#62]
## **Feature Description**

- 좌측 상단에 프로필 사진과 로그인 할때 등록했던 닉네임을 표시해줍니다.
- 첫번째 줄 :  scrap에서 데이터베이스에 북마크 저장한 데이터를 가로 리사이클러뷰로 표시해줍니다.
- 두번째 줄 : 커뮤니티에서 가장 인기있는 글을 가로 리사이클러뷰로 표시해줍니다.
- 세번째 줄 : 가장 최신 가계부를 표시해줍니다.
- 각 줄의 우측 화살표를 누르면 해당 페이지로 바로 이동됩니다.

## **Todo list**

- [x] 좌측 상단에 프로필 사진과 닉네임 데이터 넣기
- [x] scrap에서 마지막 검색기록 firebase에 저장하고 home에서 다시 불러오기
- [x] 데이터베이스 아이템 삭제&추가 실시간 갱신되어 화면에 표시됩니다. 
- [x] 스크랩 아이템 클릭 시 해당 블로그로 이동됩니다.
- [x] 커뮤니티에 작성된 글 중에서 좋아요가 가장 많은 글이 인기글에 표시됩니다.
- [x] 인기글 아이템 클릭 시 해당 게시판 디테일 페이지로 이동됩니다.  
- [x] 인기글 UI를 그리드뷰 2열 가로형으로 변경했습니다.
- [x] 데이터의 이미지가 비었을때 기본이미지를 추가했습니다.  
- [] 가계부
