### ISSUE TITLE
내정보 페이지 중간발표전까지 기능

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#86]
## **Feature Description**

- Edit → 아이콘으로 변경
- 사용자 프로필 이미지, 구글아이디, 닉네임 받아와 표시하기
- 스크랩 목록 받아와 적용하기
- 내 글 목록 받아와 적용하기

## **Todo list**

- [x] Edit -> 아이콘 변경
- [x] 사용자 프로필 정보 받아와 View 적용하기
- [x] MyPage Firebase에서 불러와 View에 표시
