### ISSUE TITLE
Home 페이지 Scrap불러오기 리펙토링

### ISSUE THREAD

**Issue by seojh5939** [LESSERAFIM-Aespa/TripMate#90]
## **Feature Description**

- 현재 홈 Fragment에서 직접 ScrapData를 불러오는 로직이 있는데 MVVM구조로 변경하고자합니다.

## **Todo list**

- [x] GetFirebaseScrapData UseCase 이용하여 ViewModel에서 데이터 불러와 적용하기 
- [x] Scrap 페이지 MVVM 리펙토링
- [x] Home 및 MyPage context 사용방식 변경
- [x] Home MVVM 리펙토링
