### ISSUE TITLE
Community UI+기능

### ISSUE THREAD

**Issue by seongssu** [LESSERAFIM-Aespa/TripMate#93]
## **Feature Description**

- Community UI 
- 프로필 사진 클릭 시 myPage로 이동됩니다.
- 좋아요를 누르면 숫자가 1 증가하거나 감소합니다.
- 좋아요를 눌렀을때 적용된 숫자를 파이어베이스에 저장합니다.
- 아이템뷰를 롱 클릭하면 데이터베이스에 북마크 저장됩니다.
- 블로그 사진 클릭 시 블로그로 이동됩니다.
- 블로그 사진 클릭 시 views가 1 증가합니다.
## **Todo list**

- [x] UI
- [x] 프로필 사진 클릭시 myPage로 이동
- [x] 좋아요 누르면 숫자 증감
- [x] 좋아요 숫자를 파이어베이스에 저장합니다.  
- [x] 북마크 데이터베이스에 저장
- [x] views 증감  데이터베이스에 저장
